### PR TITLE
Update task-scheduler.dart

### PR DESCRIPTION
**Pull request by BambinoRiya**
Create addTask function in class

### CODE REVIEW

**Comment by SandyBridge101** [comment]
Can you try making the TaskScheduler.taskList property private, aside from that everything is okay.

**Review by SandyBridge101 — APPROVED** [review]

**Comment by BambinoRiya** [comment]
Ok sure, on it!

**Comment by BambinoRiya** [comment]
> Can you try making the TaskScheduler.taskList property private, aside from that everything is okay.

Can you explain why that is a better option?

**Comment by BambinoRiya** [comment]
Conflict resolved

**Comment by SandyBridge101** [comment]
Making the TaskScheduler.taskList property private will prevent other methods from foreign classes from altering it.

**Pull request merged**
